import os
import aiohttp
import asyncio
import json
import redis.asyncio as redis
from app.models.lru_cache import LRUCache
from app.helpers.security import hash_input

# Environment Variables
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379")

# Caches
redis_client = redis.from_url(REDIS_URL, decode_responses=True)
lru_cache = LRUCache(capacity=1000)

async def ask_gemini(question: str) -> str:
    """Conversational Gemini powered chatbot that only answers election related questions and redirects off topic questions politely"""
    
    # Check LRU Cache (L1)
    q_hash = hash_input(question.lower().strip())
    l1_result = lru_cache.get(q_hash)
    if l1_result is not None:
        return l1_result

    # Check Redis Cache (L2)
    try:
        l2_result = await redis_client.get(f"faq:{q_hash}")
        if l2_result:
            lru_cache.put(q_hash, l2_result)
            return l2_result
    except Exception as e:
        # Ignore redis error if redis is down
        print(f"Redis error: {e}")

    # Gemini API Call (Async)
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    system_instruction = (
        "You are an Election Process Education Assistant. Your ONLY purpose is to answer questions "
        "related to the election process, voting, democracy, and civic duties. "
        "If a user asks anything unrelated to elections or voting, you must politely decline "
        "and redirect them to ask about election-related topics. Keep answers concise."
    )
    
    payload = {
        "contents": [{"parts": [{"text": f"System Instruction: {system_instruction}\n\nUser Question: {question}"}]}],
        "generationConfig": {
            "temperature": 0.2,
            "maxOutputTokens": 800,
        }
    }
    
    try:
        # Using connection pooling from aiohttp
        async with aiohttp.ClientSession() as session:
            async with session.post(url, headers=headers, json=payload, timeout=10) as response:
                if response.status == 200:
                    data = await response.json()
                    try:
                        answer = data['candidates'][0]['content']['parts'][0]['text']
                    except (KeyError, IndexError):
                        answer = "I'm sorry, I couldn't generate an answer for that."
                    
                    # Update Caches
                    lru_cache.put(q_hash, answer)
                    try:
                        await redis_client.set(f"faq:{q_hash}", answer, ex=86400) # 24h cache
                    except Exception:
                        pass
                        
                    return answer
                else:
                    error_text = await response.text()
                    print(f"Gemini API Error: {error_text}")
                    return "I'm sorry, my election servers are currently overloaded. Please try again later."
    except asyncio.TimeoutError:
         return "The request timed out. Please try again."
    except Exception as e:
        print(f"Gemini Exception: {e}")
        return "An unexpected error occurred."


async def generate_quiz() -> list:
    """Dynamic quiz section with 5 multiple choice questions generated by Gemini"""
    cache_key = "election_quiz_daily"
    
    # Try redis first
    try:
        cached_quiz = await redis_client.get(cache_key)
        if cached_quiz:
            return json.loads(cached_quiz)
    except Exception:
        pass
        
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt = (
        "Generate 5 multiple choice questions about the general election process and voting. "
        "Return ONLY a valid JSON array of objects. Each object should have: "
        "'question' (string), 'options' (array of 4 strings), and 'answer' (string, matching one option exactly)."
    )
    
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.7}
    }
    
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(url, headers=headers, json=payload, timeout=15) as response:
                if response.status == 200:
                    data = await response.json()
                    text = data['candidates'][0]['content']['parts'][0]['text']
                    # Clean markdown formatting if present
                    text = text.replace('```json', '').replace('```', '').strip()
                    quiz_data = json.loads(text)
                    
                    try:
                        await redis_client.set(cache_key, json.dumps(quiz_data), ex=3600) # Cache for 1 hour
                    except Exception:
                        pass
                        
                    return quiz_data
                else:
                    return []
    except Exception as e:
        print(f"Quiz Generation Error: {e}")
        return []
