import os
import aiohttp
import asyncio
import json
import redis.asyncio as redis
from dotenv import load_dotenv
load_dotenv()
from app.models.lru_cache import LRUCache
from app.helpers.security import hash_input

# Environment Variables
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379")

if not GEMINI_API_KEY:
    print("CRITICAL WARNING: GEMINI_API_KEY IS EMPTY! Check your .env file.")
else:
    print(f"DEBUG: GEMINI_API_KEY LOADED: {GEMINI_API_KEY[:5]}...{GEMINI_API_KEY[-5:]}")

# Caches
redis_client = redis.from_url(REDIS_URL, decode_responses=True)
lru_cache = LRUCache(capacity=1000)

LANG_MAP = {
    'en': 'English', 'hi': 'Hindi', 'bn': 'Bengali', 'te': 'Telugu',
    'mr': 'Marathi', 'ta': 'Tamil', 'ur': 'Urdu', 'gu': 'Gujarati',
    'kn': 'Kannada', 'or': 'Odia', 'pa': 'Punjabi', 'ml': 'Malayalam',
    'es': 'Spanish', 'fr': 'French', 'ar': 'Arabic', 'zh': 'Chinese',
    'ru': 'Russian', 'ja': 'Japanese', 'de': 'German', 'pt': 'Portuguese'
}

async def ask_gemini(question: str, target_lang: str = 'en') -> str:
    """Conversational Gemini powered chatbot that only answers election related questions and redirects off topic questions politely"""
    
    # Check LRU Cache (L1)
    q_hash = hash_input(question.lower().strip() + target_lang)
    l1_result = lru_cache.get(q_hash)
    if l1_result is not None:
        return l1_result

    # Check Redis Cache (L2)
    try:
        l2_result = await redis_client.get(f"faq:{q_hash}")
        if l2_result:
            lru_cache.put(q_hash, l2_result)
            return l2_result
    except Exception as e:
        # Ignore redis error if redis is down
        print(f"Redis error: {e}")

    # Gemini API Call (Async)
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    lang_name = LANG_MAP.get(target_lang, 'English')
    system_instruction = (
        "You are VOTY, an Election Process Education Assistant. Your ONLY purpose is to answer questions "
        "related to the election process, voting, democracy, and civic duties. "
        "If asked about e-EPIC or Form 6, you must act as a Service-Clerk and guide them step-by-step through the digital requirements. "
        f"CRITICAL RULE: You MUST ignore the input language and respond to the user ENTIRELY in {lang_name}. "
        f"Even if the user asks in English, your response must be in {lang_name}."
        "Keep answers concise."
    )
    
    payload = {
        "contents": [{"parts": [{"text": f"System Instruction: {system_instruction}\n\nUser Question: {question}"}]}],
        "generationConfig": {
            "temperature": 0.2,
            "maxOutputTokens": 800,
        }
    }
    
    try:
        # Using connection pooling from aiohttp
        async with aiohttp.ClientSession() as session:
            async with session.post(url, headers=headers, json=payload, timeout=10) as response:
                if response.status == 200:
                    data = await response.json()
                    try:
                        answer = data['candidates'][0]['content']['parts'][0]['text']
                    except (KeyError, IndexError):
                        answer = "I'm sorry, I couldn't generate an answer for that."
                    
                    # Update Caches
                    lru_cache.put(q_hash, answer)
                    try:
                        await redis_client.set(f"faq:{q_hash}", answer, ex=86400) # 24h cache
                    except Exception:
                        pass
                        
                    return answer
                else:
                    error_text = await response.text()
                    print(f"Gemini API Error: {error_text}")
                    return f"VOTY DEBUG: Gemini API Error ({response.status}). Please check your API key or quota."
    except asyncio.TimeoutError:
         return "VOTY DEBUG: Request timed out. Please check your internet connection."
    except Exception as e:
        print(f"Gemini Exception: {e}")
        return f"VOTY DEBUG: Internal Exception: {str(e)}"


async def generate_quiz(target_lang: str = 'en') -> list:
    """Dynamic quiz section with 5 multiple choice questions generated by Gemini"""
    cache_key = f"election_quiz_daily_{target_lang}"
    
    # Try redis first
    try:
        cached_quiz = await redis_client.get(cache_key)
        if cached_quiz:
            return json.loads(cached_quiz)
    except Exception:
        pass
        
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt = (
        f"Generate 5 multiple choice questions about the general election process and voting. "
        f"CRITICAL: The entire output MUST be written in the language corresponding to ISO code: '{target_lang}'. "
        "Return ONLY a valid JSON array of objects. Each object should have: "
        "'question' (string), 'options' (array of 4 strings), and 'answer' (string, matching one option exactly)."
    )
    
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.7}
    }
    
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(url, headers=headers, json=payload, timeout=15) as response:
                if response.status == 200:
                    data = await response.json()
                    text = data['candidates'][0]['content']['parts'][0]['text']
                    # Clean markdown formatting if present
                    text = text.replace('```json', '').replace('```', '').strip()
                    quiz_data = json.loads(text)
                    
                    try:
                        await redis_client.set(cache_key, json.dumps(quiz_data), ex=3600) # Cache for 1 hour
                    except Exception:
                        pass
                        
                    return quiz_data
                else:
                    return [
                        {
                            "question": "What is the primary purpose of an election?",
                            "options": ["To collect taxes", "To choose leaders and representatives", "To enforce laws", "To manage businesses"],
                            "answer": "To choose leaders and representatives"
                        },
                        {
                             "question": "Who is eligible to vote in most democratic national elections?",
                             "options": ["Only property owners", "Anyone over 10 years old", "Citizens who meet the minimum age requirement", "Only government employees"],
                             "answer": "Citizens who meet the minimum age requirement"
                        }
                    ]
    except Exception as e:
        print(f"Quiz Generation Error: {e}")
        return [
            {
                "question": "What is the primary purpose of an election?",
                "options": ["To collect taxes", "To choose leaders and representatives", "To enforce laws", "To manage businesses"],
                "answer": "To choose leaders and representatives"
            },
            {
                 "question": "Who is eligible to vote in most democratic national elections?",
                 "options": ["Only property owners", "Anyone over 10 years old", "Citizens who meet the minimum age requirement", "Only government employees"],
                 "answer": "Citizens who meet the minimum age requirement"
            }
        ]
